export const phases = [
  {
    id: 0,
    label: "Phase 1",
    name: "CRM Setup",
    goal: "Build the foundation — contacts, fields, pipeline (CEO-only setup)",
    badge: "Foundation",
    badgeColor: "background:#E1F5EE;color:#085041",
    numColor: "background:#9FE1CB;color:#085041",
    tipColor: "border-color:#1D9E75;background:#E1F5EE;color:#085041",
    alerts: [
      { type: "fix", text: "<strong>FIXED:</strong> Currency changed from INR → <strong>USD</strong>. This is a US tequila company selling globally." },
      { type: "fix", text: "<strong>FIXED:</strong> Lead Status dropdown expanded to support full follow-up logic: New → Contacted → Followed-up-1 → Followed-up-2 → Followed-up-3 → Replied → Stalled → Re-engaged → Cold → Archived" },
    ],
    steps: [
      { title: "Sign up & access HubSpot CRM", desc: "Go to hubspot.com and create a free account. The free tier covers contacts, deals, and basic automation.", tip: "Use your company email — not personal. Affects email deliverability." },
      { title: "Set company profile to USD", desc: "Settings → Account Defaults. Set currency to USD, time zone to your base (Houston/CST), and upload company logo.", tip: "Set currency before any deals are created — it cannot be changed after." },
      { title: "Create Expo Source property", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: Singapore Expo, Delhi Trade Fair, Mumbai Build Expo, Bangalore Expo, Website, Referral.", tip: "This exact value goes into your email as 'We met in Singapore' — spelling must match your CSV." },
      { title: "Create Lead Status property (expanded)", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: New, Contacted, Followed-up-1, Followed-up-2, Followed-up-3, Replied, Stalled, Re-engaged, Cold, Archived.", tip: "Each status maps to a workflow step — don't rename or abbreviate these values later." },
      { title: "Create Expo Follow-up Date property", desc: "Settings → Properties → Contact → Create. Type: Date. This is the Monday after the expo — it triggers your Day 1 email automation.", tip: "This is the trigger date for the entire sequence. Every expo import needs this filled in." },
      { title: "Create Lead Type property", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: Bulk Liquid, Private Label, General.", tip: "Bulk Liquid = CEO handles. Private Label = routes to project manager. This determines who follows up." },
      { title: "Create Expo Name property", desc: "Settings → Properties → Contact → Create. Type: Single-line text. Stores the specific expo name (e.g. 'Singapore Expo 2025') so emails can say 'we met in Singapore.'", tip: "Different from Expo Source — Source is a category, Expo Name is the specific event." },
      { title: "Build pipeline stages", desc: "CRM → Deals → Manage Pipelines → Add Stage. Create: New Lead → Contacted → Interested → Proposal Sent → Negotiation → Closed Won → Closed Lost.", tip: "Set probability % on each stage — HubSpot uses this for revenue forecasting automatically." },
      { title: "Connect Gmail or Outlook inbox", desc: "Settings → Integrations → Email → Connect your personal work inbox. Required for reply detection and same-thread follow-ups.", tip: "Do this before building any workflow — reply detection won't work without inbox connected." },
    ],
  },
  {
    id: 1,
    label: "Phase 2",
    name: "Lead Capture",
    goal: "Get every expo lead into HubSpot — tagged and ready",
    badge: "Capture",
    badgeColor: "background:#FAEEDA;color:#633806",
    numColor: "background:#FAC775;color:#633806",
    tipColor: "border-color:#BA7517;background:#FAEEDA;color:#633806",
    alerts: [
      { type: "good", text: "<strong>✅ Core flow is correct:</strong> CSV import is the right primary method. Expo is the main lead source." },
      { type: "fix", text: "<strong>FIXED:</strong> Added Expo Name as a separate import column. Expo Source = category (e.g. 'Expo'). Expo Name = specific event (e.g. 'Singapore Expo 2025'). The follow-up email uses Expo Name to say 'we met in Singapore.'" },
    ],
    steps: [
      { title: "Prepare your expo CSV", desc: "Use the CSV template already built. Columns: First Name, Last Name, Email, Phone, Company, Expo Source, Expo Name, Lead Status, Expo Follow-up Date, Lead Type.", tip: "Set Expo Follow-up Date = the Monday after the event for every row. Leave blank for website/referral leads." },
      { title: "Import CSV into HubSpot", desc: "CRM → Contacts → Import → File → Map each column to the correct property. Run import. Check for errors on the confirmation screen.", tip: "If any property doesn't exist yet, HubSpot will skip that column silently. Create all properties first (Phase 1)." },
      { title: "Verify import in New Leads view", desc: "CRM → Contacts → Filter: Lead Status = New. All imported leads should appear here. Spot-check 5 contacts for correct Expo Name, Follow-up Date, and Lead Type.", tip: "This is your daily inbox. Pin it to the sidebar for your team." },
      { title: "Tag each expo as a separate import", desc: "When importing Singapore leads, keep them separate from Delhi leads. Label the import file clearly: 'Singapore-Expo-May2025.csv'. This keeps audit trails clean.", tip: "HubSpot stores import history — named imports make it easy to find and fix errors later." },
    ],
  },
  {
    id: 2,
    label: "Phase 3",
    name: "Follow-up Automation",
    goal: "Python + Gmail API — 4-email sequence on the SAME thread, fully throttled",
    badge: "Core",
    badgeColor: "background:#E6F1FB;color:#0C447C",
    numColor: "background:#B5D4F4;color:#0C447C",
    tipColor: "border-color:#185FA5;background:#E6F1FB;color:#0C447C",
    alerts: [
      { type: "fix", text: "<strong>DECIDED — Stack confirmed:</strong> Python on the same server as Project #1. Gmail API for sending (threadId + In-Reply-To headers for same-thread replies). HubSpot Python SDK for all CRM read/write. APScheduler or cron for scheduling delays. No n8n. No HubSpot Sales Hub required." },
      { type: "fix", text: "<strong>FIXED — Throttling built in:</strong> Max 100–150 emails/day during warmup, ramp to 300/day max. Randomized send intervals (not all at once). Business hours only: 9am–5pm sender timezone. Skip weekends. All enforced in the Python scheduler." },
      { type: "fix", text: "<strong>FIXED — Reply detection stops sequence immediately:</strong> Gmail API watches the thread. If a reply arrives on any thread → Python marks Lead Status = Replied in HubSpot via SDK → cancels all pending APScheduler jobs for that contact. No more follow-ups sent." },
      { type: "fix", text: "<strong>FIXED — Stalled conversation logic added:</strong> If lead replies but conversation goes quiet for X days → Python detects no new activity → sets Lead Status = Stalled → triggers a re-engagement message on the same thread." },
      { type: "info", text: "<strong>Email format:</strong> Plain text or minimal HTML only. No tracking pixels. No unsubscribe footer. No fancy templates. These are warm follow-ups — they must read like a real person wrote them." },
      { type: "warn", text: "<strong>Pre-launch checklist:</strong> SPF, DKIM, and DMARC must be configured on the client's sending domain before going live. Without these, Gmail will route your emails to spam regardless of content." },
    ],
    steps: [
      { title: "Verify SPF / DKIM / DMARC on sending domain", desc: "Before writing a single line of code — confirm the client's domain has SPF, DKIM, and DMARC DNS records set up. Use mail-tester.com or MXToolbox to check. SPF: 'v=spf1 include:_spf.google.com ~all'. DKIM: enabled in Google Workspace Admin. DMARC: 'v=DMARC1; p=none; rua=mailto:dmarc@yourdomain.com'.", tip: "This is the #1 reason cold outreach lands in spam. Do not skip. Even warm follow-ups get filtered without proper DNS records." },
      { title: "Set up Gmail API credentials", desc: "Google Cloud Console → Create Project → Enable Gmail API → OAuth 2.0 credentials → Download credentials.json. Run the auth flow once to generate token.json. Store both files securely on the server — never commit to git.", tip: "Use a dedicated sending Gmail account (e.g. outreach@yourdomain.com), not the CEO's personal inbox. Keeps sending reputation separate." },
      { title: "Install Python dependencies on server", desc: "pip install google-auth google-auth-oauthlib google-api-python-client hubspot-api-client apscheduler. Pin versions in requirements.txt. Set up a virtualenv. This runs on the same server as Project #1.", tip: "Run 'pip freeze > requirements.txt' after install. Anyone deploying later needs exact versions — minor version mismatches break Gmail API auth." },
      { title: "Write all 4 email templates (plain text)", desc: "Write as plain .txt files or Python strings. Day 1: intro + brochure link (not attachment — link to hosted PDF). Day 3: case study (Iraq container example). Day 7: ask Bulk Liquid or Private Label? Day 14: last nudge. Use {expo_name}, {first_name}, {lead_type} as placeholders.", tip: "Keep Day 1 under 100 words. No HTML, no images, no unsubscribe link. The goal is to look like a real email from a real person — not a marketing blast." },
      { title: "Build the Gmail API send function (with threading)", desc: "Python function: send_email(to, subject, body, thread_id=None, message_id=None). For Day 1: no thread_id → Gmail creates a new thread → store returned threadId and messageId in HubSpot contact properties. For Days 3/7/14: pass stored threadId and set In-Reply-To header to previous messageId → Gmail appends to same thread.", tip: "Store threadId and last_message_id as custom HubSpot contact properties after every send. These are required for threading — if you lose them, the next email starts a new thread." },
      { title: "Build the APScheduler job queue with throttling", desc: "On CSV import: for each contact, schedule 4 jobs — Day 1 (Monday after expo), Day 3, Day 7, Day 14. Throttle: max 150 sends/day during warmup (first 2 weeks), then ramp to 300/day max. Randomize send time within 9am–5pm sender timezone window. Skip Saturday and Sunday. Use APScheduler's JobStore (SQLite or PostgreSQL) so jobs survive server restarts.", tip: "Randomize intervals: instead of sending all Day-1 emails at 9:00am, spread them across 9am–5pm with random offsets. Sending 100 identical emails at the same second is a spam signal." },
      { title: "Build the reply detection loop", desc: "Python cron job runs every 15–30 minutes. For each active contact with a threadId: call Gmail API threads.get() → check if any message in thread is FROM the lead (not from us). If reply found → call HubSpot SDK → set Lead Status = Replied → cancel all pending APScheduler jobs for that contact_id → log the reply timestamp.", tip: "Check sender address carefully — Gmail threads include your own sent messages. Only flag as 'replied' if the message is from the lead's email address, not your sending address." },
      { title: "Build the stalled conversation detector", desc: "Separate cron job runs daily. Query HubSpot SDK for contacts where Lead Status = Replied AND last_reply_date < (today - X days). For each stalled contact: send a re-engagement message on the same Gmail thread (use stored threadId) → set Lead Status = Stalled in HubSpot. X days = configurable, start with 14.", tip: "Make X configurable in a config.py file — the client may want to adjust this. 14 days is a good default for B2B tequila sales." },
      { title: "Test end-to-end with yopmail contacts", desc: "Import 7 yopmail test contacts with Expo Follow-up Date = tomorrow. Verify: Day 1 sends at correct time → check yopmail inbox → reply from yopmail → verify reply detection fires within 30 min → verify no Day 3 sends → verify Lead Status = Replied in HubSpot. Then let a thread go stale → verify Stalled logic fires.", tip: "Test on a Thursday so Day 3 falls on Monday — same as real expo timing. Check spam folder in yopmail. If Day 1 lands in spam, fix SPF/DKIM before going live." },
    ],
  },
  {
    id: 3,
    label: "Phase 4",
    name: "Deal Tracking",
    goal: "Light pipeline — visibility only, not full CRM rollout",
    badge: "Revenue",
    badgeColor: "background:#EEEDFE;color:#3C3489",
    numColor: "background:#CECBF6;color:#3C3489",
    tipColor: "border-color:#534AB7;background:#EEEDFE;color:#3C3489",
    alerts: [
      { type: "warn", text: "<strong>Scope note:</strong> Full deal tracking was NOT in the agreed Tier 1 scope. Core deliverable is follow-up automation + CRM. Keep this phase light — basic pipeline visibility only. Do not let it delay Phase 3." },
      { type: "info", text: "<strong>Recommendation:</strong> Set up the pipeline stages now (already done in Phase 1), but only start moving deals when leads actually reply. Don't build reports or forecasting until the follow-up sequence is live and working." },
    ],
    steps: [
      { title: "Create deal when lead replies", desc: "Workflow step: Lead Status changes to Replied → auto-create Deal → associate with contact → set Deal Stage = Interested → assign to lead owner.", tip: "Keep it automatic. Reps should not be manually creating deals — things get missed." },
      { title: "Fill in deal amount and close date", desc: "When a deal is created, the owner opens it and adds: estimated amount (USD), expected close date, Deal Type (Bulk Liquid or Private Label).", tip: "Even a rough estimate matters. $0 pipeline = useless forecasting. Push for a number even if approximate." },
      { title: "Use the board view for weekly review", desc: "CRM → Deals → Board View. Once a week, drag stale deals forward or mark Closed Lost. 15 minutes max.", tip: "This is the only reporting needed at this stage. Don't build dashboards until you have 30+ real deals." },
    ],
  },
  {
    id: 4,
    label: "Phase 5",
    name: "Re-engagement",
    goal: "Quarterly re-touch for ALL leads — not just cold ones",
    badge: "Recovery",
    badgeColor: "background:#FAECE7;color:#712B13",
    numColor: "background:#F5C4B3;color:#712B13",
    tipColor: "border-color:#993C1D;background:#FAECE7;color:#712B13",
    alerts: [
      { type: "fix", text: "<strong>FIXED — Logic corrected:</strong> Previous version was 60-day cold lead recovery only. Client's actual requirement: re-touch ALL leads every 90 days regardless of status — so leads stay alive in the system forever. 'I know we're leaving business on the table by not going back to them.'" },
      { type: "info", text: "<strong>Flow:</strong> 90 days after last contact → re-engagement email → if reply → route to deal flow → if no reply after 2 touches → mark Cold → if still no reply → Archived." },
    ],
    steps: [
      { title: "Build the quarterly re-engagement workflow", desc: "Automation → Workflows. Trigger: Last Activity Date > 90 days AND Lead Status is NOT Archived. Action: Send re-engagement email → wait 14 days → if no reply → send second email → wait 14 days → if still no reply → set status Cold.", tip: "Set re-enrollment ON so contacts re-enter this workflow every 90 days automatically." },
      { title: "Write the re-engagement email", desc: "Subject: 'Still relevant for you?' Body should feel different — reference the expo you met at, mention a new product update or case study. Keep it personal, not templated.", tip: "This email performs best when it references something specific — use {{ contact.expo_name }} and {{ contact.lead_type }}." },
      { title: "Route replies back to deal flow", desc: "If reply detected in re-engagement workflow → set Lead Status = Re-engaged → enroll in deal creation workflow (Phase 4 Step 1) automatically.", tip: "A recovered lead should flow into the pipeline exactly like a fresh reply. No manual steps." },
      { title: "Archive truly dead leads", desc: "After 2 re-engagement touches with no reply → set Lead Status = Archived. Create a saved view: Lead Status = Archived. Review quarterly — some leads may be worth a personal email from the CEO.", tip: "Never delete contacts. Archived keeps them out of workflows but preserves history." },
    ],
  },
  {
    id: 5,
    label: "Phase 6",
    name: "Reporting + Hosting",
    goal: "Dashboard + same server deployment — per proposal commitment",
    badge: "Infrastructure",
    badgeColor: "background:#E8F4FD;color:#0C447C",
    numColor: "background:#B5D4F4;color:#0C447C",
    tipColor: "border-color:#1A73E8;background:#E8F4FD;color:#0C447C",
    alerts: [
      { type: "fix", text: "<strong>FIXED — Pricing automation removed from this build.</strong> Client said clearly: 'pricing comes after the CRM is done.' That is Project #3. It does NOT belong in this phase." },
      { type: "new", text: "<strong>ADDED — Hosting:</strong> Client agreed deployment goes on the same server as Project #1. This needs to be in the plan explicitly." },
      { type: "new", text: "<strong>ADDED — Handwritten card integration:</strong> Webhook needed when lead enters CRM → triggers card system → card-sent status writes back to HubSpot contact. Both tracks must talk to each other." },
      { type: "new", text: "<strong>ADDED — Reporting dashboard:</strong> This was quoted in the proposal. Needs a dedicated phase — not scattered across other steps." },
    ],
    steps: [
      { title: "Deploy on same server as Project 1", desc: "Use the existing server infrastructure. Deploy the Python follow-up service (Phase 3), HubSpot webhook endpoints, and APScheduler daemon on the same instance. Give client one URL to access everything.", tip: "Document the server URL and credentials in a shared note — not just in your head. Set up systemd or supervisor to keep the Python scheduler running after reboots." },
      { title: "Set up handwritten card webhook", desc: "When a new contact is created in HubSpot → trigger webhook → pass contact name, company, expo name, and address to the card system → card system sends back 'card-sent' status → write that back to HubSpot contact as a property.", tip: "Add a 'Card Sent' checkbox property in HubSpot (Phase 1) so you can filter: contacts who got a card vs didn't." },
      { title: "Build the reporting dashboard", desc: "Reports → Create Report → save these 3: (1) Leads by Expo Source this quarter, (2) Follow-up sequence completion rate, (3) Replied leads by Lead Type.", tip: "Share dashboard link with CEO weekly. This replaces any manual spreadsheet tracking." },
      { title: "Write SOPs and handover docs", desc: "Document: how to import expo CSV, how to trigger the follow-up workflow, how to check the dashboard. Store in HubSpot's built-in wiki or a pinned Notion page.", tip: "The client is the only user right now. The SOP protects against him forgetting the process in 3 months." },
    ],
  },
];
