export const phases = [
  {
    id: 0,
    label: "Phase 1",
    name: "CRM Setup",
    goal: "Build the foundation — contacts, fields, pipeline (CEO-only setup)",
    badge: "Foundation",
    badgeColor: "background:#E1F5EE;color:#085041",
    numColor: "background:#9FE1CB;color:#085041",
    tipColor: "border-color:#1D9E75;background:#E1F5EE;color:#085041",
    alerts: [
      { type: "fix", text: "<strong>FIXED:</strong> Currency changed from INR → <strong>USD</strong>. This is a US tequila company selling globally." },
      { type: "fix", text: "<strong>FIXED:</strong> Team invite step removed. Client said 'baby steps — just for me first.' Only CEO + Evelyn for now. Team rollout is a future phase." },
      { type: "fix", text: "<strong>FIXED:</strong> Lead Status dropdown expanded to support full follow-up logic: New → Contacted → Followed-up-1 → Followed-up-2 → Followed-up-3 → Replied → Stalled → Re-engaged → Cold → Archived" },
    ],
    steps: [
      { title: "Sign up & access HubSpot CRM", desc: "Go to hubspot.com and create a free account. The free tier covers contacts, deals, and basic automation.", tip: "Use your company email — not personal. Affects email deliverability." },
      { title: "Set company profile to USD", desc: "Settings → Account Defaults. Set currency to USD, time zone to your base (Houston/CST), and upload company logo.", tip: "Set currency before any deals are created — it cannot be changed after." },
      { title: "Create Expo Source property", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: Singapore Expo, Delhi Trade Fair, Mumbai Build Expo, Bangalore Expo, Website, Referral.", tip: "This exact value goes into your email as 'We met in Singapore' — spelling must match your CSV." },
      { title: "Create Lead Status property (expanded)", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: New, Contacted, Followed-up-1, Followed-up-2, Followed-up-3, Replied, Stalled, Re-engaged, Cold, Archived.", tip: "Each status maps to a workflow step — don't rename or abbreviate these values later." },
      { title: "Create Expo Follow-up Date property", desc: "Settings → Properties → Contact → Create. Type: Date. This is the Monday after the expo — it triggers your Day 1 email automation.", tip: "This is the trigger date for the entire sequence. Every expo import needs this filled in." },
      { title: "Create Lead Type property", desc: "Settings → Properties → Contact → Create. Type: Dropdown. Values: Bulk Liquid, Private Label, General.", tip: "Bulk Liquid = CEO handles. Private Label = routes to project manager. This determines who follows up." },
      { title: "Create Expo Name property", desc: "Settings → Properties → Contact → Create. Type: Single-line text. Stores the specific expo name (e.g. 'Singapore Expo 2025') so emails can say 'we met in Singapore.'", tip: "Different from Expo Source — Source is a category, Expo Name is the specific event." },
      { title: "Build pipeline stages", desc: "CRM → Deals → Manage Pipelines → Add Stage. Create: New Lead → Contacted → Interested → Proposal Sent → Negotiation → Closed Won → Closed Lost.", tip: "Set probability % on each stage — HubSpot uses this for revenue forecasting automatically." },
      { title: "Connect Gmail or Outlook inbox", desc: "Settings → Integrations → Email → Connect your personal work inbox. Required for reply detection and same-thread follow-ups.", tip: "Do this before building any workflow — reply detection won't work without inbox connected." },
    ],
  },
  {
    id: 1,
    label: "Phase 2",
    name: "Lead Capture",
    goal: "Get every expo lead into HubSpot — tagged and ready",
    badge: "Capture",
    badgeColor: "background:#FAEEDA;color:#633806",
    numColor: "background:#FAC775;color:#633806",
    tipColor: "border-color:#BA7517;background:#FAEEDA;color:#633806",
    alerts: [
      { type: "good", text: "<strong>✅ Core flow is correct:</strong> CSV import is the right primary method. Expo is the main lead source." },
      { type: "fix", text: "<strong>FIXED:</strong> Added Expo Name as a separate import column. Expo Source = category (e.g. 'Expo'). Expo Name = specific event (e.g. 'Singapore Expo 2025'). The follow-up email uses Expo Name to say 'we met in Singapore.'" },
      { type: "info", text: "<strong>Note:</strong> Website form capture is deprioritized — client's leads come primarily from expos. Keep as future addition." },
    ],
    steps: [
      { title: "Prepare your expo CSV", desc: "Use the CSV template already built. Columns: First Name, Last Name, Email, Phone, Company, Expo Source, Expo Name, Lead Status, Expo Follow-up Date, Lead Type.", tip: "Set Expo Follow-up Date = the Monday after the event for every row. Leave blank for website/referral leads." },
      { title: "Import CSV into HubSpot", desc: "CRM → Contacts → Import → File → Map each column to the correct property. Run import. Check for errors on the confirmation screen.", tip: "If any property doesn't exist yet, HubSpot will skip that column silently. Create all properties first (Phase 1)." },
      { title: "Verify import in New Leads view", desc: "CRM → Contacts → Filter: Lead Status = New. All imported leads should appear here. Spot-check 5 contacts for correct Expo Name, Follow-up Date, and Lead Type.", tip: "This is your daily inbox. Pin it to the sidebar for your team." },
      { title: "Tag each expo as a separate import", desc: "When importing Singapore leads, keep them separate from Delhi leads. Label the import file clearly: 'Singapore-Expo-May2025.csv'. This keeps audit trails clean.", tip: "HubSpot stores import history — named imports make it easy to find and fix errors later." },
    ],
  },
  {
    id: 2,
    label: "Phase 3",
    name: "Follow-up Automation",
    goal: "Automated sequence on the SAME thread — never forget a lead",
    badge: "Core",
    badgeColor: "background:#E6F1FB;color:#0C447C",
    numColor: "background:#B5D4F4;color:#0C447C",
    tipColor: "border-color:#185FA5;background:#E6F1FB;color:#0C447C",
    alerts: [
      { type: "fix", text: "<strong>CRITICAL FIX — Same thread requirement:</strong> Client explicitly said 'follow up on the same email thread.' HubSpot's standard workflow 'Send Email' sends a NEW email each time — it does NOT thread. You must decide: (A) Use HubSpot Sequences (Sales Hub — check if your plan includes it), (B) Route sends through Gmail API via n8n to control threading, or (C) Accept new emails as a compromise. Decide this before building." },
      { type: "fix", text: "<strong>FIXED:</strong> Stalled conversation logic added. If lead replies but conversation dies → status set to Stalled → re-engagement triggers after 14 days. Previously: workflow just ended on reply." },
      { type: "warn", text: "<strong>Note:</strong> 4 email steps included (Day 1, 3, 7, 14). Align with what was quoted to the client — 3 or 4 follow-ups. Either works technically." },
    ],
    steps: [
      { title: "Decide: same-thread approach", desc: "Before building anything — pick your threading method. Option A: HubSpot Sequences (Sales Hub). Option B: Gmail API via n8n (recommended if you have n8n running). Option C: Accept new emails per follow-up.", tip: "Check your HubSpot plan first. Free plan does NOT include Sequences. Starter ($20/mo) does." },
      { title: "Write all 4 email templates", desc: "Marketing → Email → Create Email → Save as Template. Day 1: intro + brochure. Day 3: case study (Iraq container example). Day 7: ask Bulk Liquid or Private Label? Day 14: last nudge.", tip: "Day 1 must be under 100 words. Attach brochure to Day 1 only. Use {{ contact.expo_name }} to personalize location." },
      { title: "Create the follow-up workflow", desc: "Automation → Workflows → Contact-based. Trigger: Expo Follow-up Date = today. Steps: Send Day 1 → set status Followed-up-1 → wait 2 days → Send Day 3 → set status Followed-up-2 → wait 4 days → Send Day 7 → set status Followed-up-3 → wait 7 days → Send Day 14.", tip: "Use 'Expo Follow-up Date = today' as trigger so each expo batch fires on its own Monday automatically." },
      { title: "Add reply detection branch", desc: "After each email step, add IF/THEN: If contact replied → set Lead Status = Replied → remove from sequence → notify lead owner. This stops follow-ups the moment someone responds.", tip: "Reply detection only works if inbox is connected (Phase 1 Step 9). Test this with a yopmail contact first." },
      { title: "Add stalled conversation logic", desc: "Create a second workflow. Trigger: Lead Status = Replied AND Last Activity Date > 14 days ago. Action: Set status = Stalled → Send re-engagement email → wait 7 days → if no reply → set Cold.", tip: "This is the logic the client specifically asked for — 'even if the conversation stalls, keep following up.'" },
      { title: "Test with yopmail contacts", desc: "Import your 7 yopmail test contacts. Manually trigger the workflow. Check yopmail.com inboxes to confirm Day 1 arrives, reply detection stops the sequence, and threading works as chosen.", tip: "Test on a Friday so Day 3 arrives Monday — same as real expo timing. Check spam folder too." },
    ],
  },
  {
    id: 3,
    label: "Phase 4",
    name: "Deal Tracking",
    goal: "Light pipeline — visibility only, not full CRM rollout",
    badge: "Revenue",
    badgeColor: "background:#EEEDFE;color:#3C3489",
    numColor: "background:#CECBF6;color:#3C3489",
    tipColor: "border-color:#534AB7;background:#EEEDFE;color:#3C3489",
    alerts: [
      { type: "warn", text: "<strong>Scope note:</strong> Full deal tracking was NOT in the agreed Tier 1 scope. Core deliverable is follow-up automation + CRM. Keep this phase light — basic pipeline visibility only. Do not let it delay Phase 3." },
      { type: "info", text: "<strong>Recommendation:</strong> Set up the pipeline stages now (already done in Phase 1), but only start moving deals when leads actually reply. Don't build reports or forecasting until the follow-up sequence is live and working." },
    ],
    steps: [
      { title: "Create deal when lead replies", desc: "Workflow step: Lead Status changes to Replied → auto-create Deal → associate with contact → set Deal Stage = Interested → assign to lead owner.", tip: "Keep it automatic. Reps should not be manually creating deals — things get missed." },
      { title: "Fill in deal amount and close date", desc: "When a deal is created, the owner opens it and adds: estimated amount (USD), expected close date, Deal Type (Bulk Liquid or Private Label).", tip: "Even a rough estimate matters. $0 pipeline = useless forecasting. Push for a number even if approximate." },
      { title: "Use the board view for weekly review", desc: "CRM → Deals → Board View. Once a week, drag stale deals forward or mark Closed Lost. 15 minutes max.", tip: "This is the only reporting needed at this stage. Don't build dashboards until you have 30+ real deals." },
    ],
  },
  {
    id: 4,
    label: "Phase 5",
    name: "Re-engagement",
    goal: "Quarterly re-touch for ALL leads — not just cold ones",
    badge: "Recovery",
    badgeColor: "background:#FAECE7;color:#712B13",
    numColor: "background:#F5C4B3;color:#712B13",
    tipColor: "border-color:#993C1D;background:#FAECE7;color:#712B13",
    alerts: [
      { type: "fix", text: "<strong>FIXED — Logic corrected:</strong> Previous version was 60-day cold lead recovery only. Client's actual requirement: re-touch ALL leads every 90 days regardless of status — so leads stay alive in the system forever. 'I know we're leaving business on the table by not going back to them.'" },
      { type: "info", text: "<strong>Flow:</strong> 90 days after last contact → re-engagement email → if reply → route to deal flow → if no reply after 2 touches → mark Cold → if still no reply → Archived." },
    ],
    steps: [
      { title: "Build the quarterly re-engagement workflow", desc: "Automation → Workflows. Trigger: Last Activity Date > 90 days AND Lead Status is NOT Archived. Action: Send re-engagement email → wait 14 days → if no reply → send second email → wait 14 days → if still no reply → set status Cold.", tip: "Set re-enrollment ON so contacts re-enter this workflow every 90 days automatically." },
      { title: "Write the re-engagement email", desc: "Subject: 'Still relevant for you?' Body should feel different — reference the expo you met at, mention a new product update or case study. Keep it personal, not templated.", tip: "This email performs best when it references something specific — use {{ contact.expo_name }} and {{ contact.lead_type }}." },
      { title: "Route replies back to deal flow", desc: "If reply detected in re-engagement workflow → set Lead Status = Re-engaged → enroll in deal creation workflow (Phase 4 Step 1) automatically.", tip: "A recovered lead should flow into the pipeline exactly like a fresh reply. No manual steps." },
      { title: "Archive truly dead leads", desc: "After 2 re-engagement touches with no reply → set Lead Status = Archived. Create a saved view: Lead Status = Archived. Review quarterly — some leads may be worth a personal email from the CEO.", tip: "Never delete contacts. Archived keeps them out of workflows but preserves history." },
    ],
  },
  {
    id: 5,
    label: "Phase 6",
    name: "Reporting + Hosting",
    goal: "Dashboard + same server deployment — per proposal commitment",
    badge: "Infrastructure",
    badgeColor: "background:#E8F4FD;color:#0C447C",
    numColor: "background:#B5D4F4;color:#0C447C",
    tipColor: "border-color:#1A73E8;background:#E8F4FD;color:#0C447C",
    alerts: [
      { type: "fix", text: "<strong>FIXED — Pricing automation removed from this build.</strong> Client said clearly: 'pricing comes after the CRM is done.' That is Project #3. It does NOT belong in this phase." },
      { type: "new", text: "<strong>ADDED — Hosting:</strong> Client agreed deployment goes on the same server as Project #1. This needs to be in the plan explicitly." },
      { type: "new", text: "<strong>ADDED — Handwritten card integration:</strong> Webhook needed when lead enters CRM → triggers card system → card-sent status writes back to HubSpot contact. Both tracks must talk to each other." },
      { type: "new", text: "<strong>ADDED — Reporting dashboard:</strong> This was quoted in the proposal. Needs a dedicated phase — not scattered across other steps." },
    ],
    steps: [
      { title: "Deploy on same server as Project 1", desc: "Use the existing server infrastructure. Set up the HubSpot integration, n8n workflows, and any webhook endpoints on the same instance. Give client one URL to access everything.", tip: "Document the server URL and credentials in a shared note — not just in your head." },
      { title: "Set up handwritten card webhook", desc: "When a new contact is created in HubSpot → trigger webhook → pass contact name, company, expo name, and address to the card system → card system sends back 'card-sent' status → write that back to HubSpot contact as a property.", tip: "Add a 'Card Sent' checkbox property in HubSpot (Phase 1) so you can filter: contacts who got a card vs didn't." },
      { title: "Build the reporting dashboard", desc: "Reports → Create Report → save these 3: (1) Leads by Expo Source this quarter, (2) Follow-up sequence completion rate, (3) Replied leads by Lead Type.", tip: "Share dashboard link with CEO weekly. This replaces any manual spreadsheet tracking." },
      { title: "Write SOPs and handover docs", desc: "Document: how to import expo CSV, how to trigger the follow-up workflow, how to check the dashboard. Store in HubSpot's built-in wiki or a pinned Notion page.", tip: "The client is the only user right now. The SOP protects against him forgetting the process in 3 months." },
    ],
  },
];
